server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: Authentication
      routes:
        - id: openapi
          uri: http://api-gateway:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:6006"
              - "http://localhost:8080"
              - "http://localhost:4173"
              - "http://localhost:4174"
              - "http://localhost:4175"
              - "http://localhost:4176"
              - "http://localhost:5173"
              - "http://localhost:5174"
              - "http://localhost:5175"
              - "http://localhost:5176"
              - "http://components-ui:4173"
              - "http://user-ui:4174"
              - "http://product-ui:4175"
              - "http://react-ui:4176"
              - "http://components-ui:5173"
              - "http://user-ui:5174"
              - "http://product-ui:5175"
              - "http://react-ui:5176"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - HEAD
              - OPTIONS
              - TRACE
              - CONNECT
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
            allowCredentials: true