server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: Authentication
      routes:
        - id: openapi
          uri: http://api-gateway:8080
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost"
              - "http://components-ui"
              - "http://user-ui"
              - "http://product-ui"
              - "http://react-ui"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - HEAD
              - OPTIONS
              - TRACE
              - CONNECT
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
            allowCredentials: true