eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    hostName: ${spring.application.name}
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
logging:
  pattern:
    console: "%yellow(%d{yyyy-MM-dd HH:mm:ss.SSSZZZZZ}) %highlight(%-5level) ${PID:-} --- %red([${spring.application.name}]) %magenta([%thread]) %cyan([%X{traceId:-}-%X{spanId:-}]) %logger : %msg %n"
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        batch_versioned_data: true
        format_sql: true
        generate_statistics: false
        jdbc:
          batch_size: 2
        order_inserts: true
        order_updates: true
    show-sql: true
user-service-url: http://users
product-service-url: http://products