eureka:
  client:
    service-url:
      default-zone: https://eureka.davidcamelo.com/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    zipkin:
      tracing:
        endpoint: https://zipkin.davidcamelo.com/api/v2/spans