server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/users?createDatabaseIfNotExist=true
jwt:
  access-token-expiration: 300000 # 3600000 -> 1 hour
  refresh-token-expiration: 3600000 # 86400000 -> 1 days