apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent
  labels:
    app: fluent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent
  template:
    metadata:
      labels:
        app: fluent
    spec:
      volumes:
        - name: fluent-data
          persistentVolumeClaim:
            claimName: fluent-data-pvc
      containers:
        - name: fluent
          image: fluent/fluentd:latest
          ports:
            - name: http
              containerPort: 24224
              protocol: TCP
            - name: udp
              containerPort: 24224
              protocol: UDP
          volumeMounts:
            - name: fluent-data
              mountPath: /fluentd/log
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 1