apiVersion: v1
kind: Service
metadata:
  name: fluent
  labels:
    app: fluent
spec:
  selector:
    app: fluent
  ports:
    - name: http
      port: 24224
      targetPort: 24224
    - name: udp
      port: 24224
      targetPort: 24224