apiVersion: v1
kind: Service
metadata:
  name: fluent
  labels:
    app: fluent
spec:
  selector:
    app: fluent
  ports:
    - name: tcp
      protocol: TCP
      port: 24224
      targetPort: 24224
    - name: udp
      protocol: UDP
      port: 24224
      targetPort: 24224